version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: cdp
    # I'm not saving volumes, because i don't want to persist data
    # volumes:
    #   - mongodb_data:/data/db

volumes:
  mongodb_data:
